export const alertsTranslations = {
    en: {
      supportTicketGenerated: 'Support ticket generated',
      enterIdNumber: 'Please enter your ID number',
      uploadIdentityImage: 'Please upload an image of your ID',
      dataSuccessfullySaved: 'Data successfully saved',
      passwordSuccessfullyChanged: 'Password successfully changed',
      deleteReportConfirmation: 'Are you sure you want to delete this report?',
      ticketNotGenerated: 'Support ticket not generated',
      selectProduct: 'Please select a product',
      enterDescription: 'Please enter a description',
      selectLevel: 'Please select a level',
      reportDeleted: 'Report deleted',
      addresRequired: 'Address is required',
      zipCodeRequired: 'Zip code is required',
      quotationDontBelongToLoggedUser: 'This quotation does not belong to the logged user',
      priceRequestSentSuccessfully: 'Price request sent successfully',
      errorHasOcurred: 'An error has occurred',
    },
    es: {
      supportTicketGenerated: 'Ticket de soporte generado',
      enterIdNumber: 'Por favor ingrese su número de identificación',
      uploadIdentityImage: 'Por favor suba una imagen de su identificación',
      dataSuccessfullySaved: 'Datos guardados exitosamente',
      passwordSuccessfullyChanged: 'Contraseña cambiada exitosamente',
      deleteReportConfirmation: '¿Está seguro de que desea eliminar este reporte?',
      ticketNotGenerated: 'Ticket de soporte no generado',
      selectProduct: 'Por favor seleccione un producto',
      enterDescription: 'Por favor ingrese una descripción',
      selectLevel: 'Por favor seleccione un nivel',
      reportDeleted: 'Reporte eliminado',
      addresRequired: 'Dirección es requerida',
      zipCodeRequired: 'Código postal es requerido',
      quotationDontBelongToLoggedUser: 'Esta cotización no pertenece al usuario logueado',
      priceRequestSentSuccessfully: 'Solicitud de precio enviada exitosamente',
      errorHasOcurred: 'Ha ocurrido un error',
    },
    fr: {
      supportTicketGenerated: 'Ticket de support généré',
      enterIdNumber: 'Veuillez entrer votre numéro d\'identification',
      uploadIdentityImage: 'Veuillez télécharger une image de votre pièce d\'identité',
      dataSuccessfullySaved: 'Données enregistrées avec succès',
      passwordSuccessfullyChanged: 'Mot de passe changé avec succès',
      deleteReportConfirmation: 'Êtes-vous sûr de vouloir supprimer ce rapport?',
      ticketNotGenerated: 'Ticket de support non généré',
      selectProduct: 'Veuillez sélectionner un produit',
      enterDescription: 'Veuillez entrer une description',
      selectLevel: 'Veuillez sélectionner un niveau',
      reportDeleted: 'Rapport supprimé',
      addresRequired: 'Adresse est requise',
      zipCodeRequired: 'Code postal est requis',
      quotationDontBelongToLoggedUser: 'Cette citation n\'appartient pas à l\'utilisateur connecté',
      priceRequestSentSuccessfully: 'Demande de prix envoyée avec succès',
      errorHasOcurred: 'Une erreur s\'est produite',
    },
    it: {
      supportTicketGenerated: 'Ticket di supporto generato',
      enterIdNumber: 'Si prega di inserire il numero di identificazione',
      uploadIdentityImage: 'Si prega di caricare un\'immagine del documento di identità',
      dataSuccessfullySaved: 'Dati salvati con successo',
      passwordSuccessfullyChanged: 'Password modificata con successo',
      deleteReportConfirmation: 'Sei sicuro di voler eliminare questo report?',
      ticketNotGenerated: 'Ticket di supporto non generato',
      selectProduct: 'Si prega di selezionare un prodotto',
      enterDescription: 'Si prega di inserire una descrizione',
      selectLevel: 'Si prega di selezionare un livello',
      reportDeleted: 'Report eliminato',
      addresRequired: 'Indirizzo richiesto',
      zipCodeRequired: 'Il codice postale è richiesto',
      quotationDontBelongToLoggedUser: 'Questa citazione non appartiene all\'utente connesso',
      priceRequestSentSuccessfully: 'Richiesta di prezzo inviata con successo',
      errorHasOcurred: 'Si è verificato un errore',
    },
    pt: {
      supportTicketGenerated: 'Bilhete de suporte gerado',
      enterIdNumber: 'Por favor, insira o número de identificação',
      uploadIdentityImage: 'Por favor, faça o upload de uma imagem do seu documento de identidade',
      dataSuccessfullySaved: 'Dados salvos com sucesso',
      passwordSuccessfullyChanged: 'Senha alterada com sucesso',
      deleteReportConfirmation: 'Tem certeza de que deseja excluir este relatório?',
      ticketNotGenerated: 'Bilhete de suporte não gerado',
      selectProduct: 'Por favor, selecione um produto',
      enterDescription: 'Por favor, insira uma descrição',
      selectLevel: 'Por favor, selecione um nível',
      reportDeleted: 'Relatório excluído',
      addresRequired: 'Endereço é obrigatório',
      zipCodeRequired: 'O código postal é obrigatório',
      quotationDontBelongToLoggedUser: 'Esta cotação não pertence ao usuário logado',
      priceRequestSentSuccessfully: 'Pedido de preço enviado com sucesso',
      errorHasOcurred: 'Ocorreu um erro',
    },
    pl: {
      supportTicketGenerated: 'Bilet wsparcia wygenerowany',
      enterIdNumber: 'Proszę podać swój numer identyfikacyjny',
      uploadIdentityImage: 'Proszę przesłać obraz swojego dokumentu tożsamości',
      dataSuccessfullySaved: 'Dane zapisane pomyślnie',
      passwordSuccessfullyChanged: 'Hasło zostało pomyślnie zmienione',
      deleteReportConfirmation: 'Czy na pewno chcesz usunąć ten raport?',
      ticketNotGenerated: 'Bilet ws parcia nie wygenerowany',
      selectProduct: 'Proszę wybrać produkt',
      enterDescription: 'Proszę wprowadzić opis',
      selectLevel: 'Proszę wybrać poziom',
      reportDeleted: 'Raport usunięty',
      addresRequired: 'Adres jest wymagany',
      zipCodeRequired: 'Kod pocztowy jest wymagany',
      quotationDontBelongToLoggedUser: 'To zapytanie nie należy do zalogowanego użytkownika',
      priceRequestSentSuccessfully: 'Zapytanie o cenę wysłane pomyślnie',
      errorHasOcurred: 'Wystąpił błąd',
    },
    nl: {
      supportTicketGenerated: 'Ondersteuningsticket gegenereerd',
      enterIdNumber: 'Voer uw ID-nummer in',
      uploadIdentityImage: 'Upload een afbeelding van uw identiteitsbewijs',
      dataSuccessfullySaved: 'Gegevens succesvol opgeslagen',
      passwordSuccessfullyChanged: 'Wachtwoord succesvol gewijzigd',
      deleteReportConfirmation: 'Weet u zeker dat u dit rapport wilt verwijderen?',
      ticketNotGenerated: 'Ondersteuningsticket niet gegenereerd',
      selectProduct: 'Selecteer een product',
      enterDescription: 'Voer een beschrijving in',
      selectLevel: 'Selecteer een niveau',
      reportDeleted: 'Rapport verwijderd',
      addresRequired: 'Adres is verplicht',
      zipCodeRequired: 'Postcode is verplicht',
      quotationDontBelongToLoggedUser: 'Deze offerte behoort niet tot de ingelogde gebruiker',
      priceRequestSentSuccessfully: 'Prijsaanvraag succesvol verzonden',
      errorHasOcurred: 'Er is een fout opgetreden',
    },
    sv: {
      supportTicketGenerated: 'Supportbiljett genererad',
      enterIdNumber: 'Ange ditt ID-nummer',
      uploadIdentityImage: 'Ladda upp en bild av ditt ID',
      dataSuccessfullySaved: 'Data sparades framgångsrikt',
      passwordSuccessfullyChanged: 'Lösenordet ändrades framgångsrikt',
      deleteReportConfirmation: 'Är du säker på att du vill ta bort denna rapport?',
      ticketNotGenerated: 'Supportbiljett inte genererad',
      selectProduct: 'Vänligen välj en produkt',
      enterDescription: 'Ange en beskrivning',
      selectLevel: 'Vänligen välj en nivå',
      reportDeleted: 'Rapport raderad',
      addresRequired: 'Adress krävs',
      zipCodeRequired: 'Postnummer krävs',
      quotationDontBelongToLoggedUser: 'Denna offert tillhör inte den inloggade användaren',
      priceRequestSentSuccessfully: 'Prisförfrågan skickades framgångsrikt',
      errorHasOcurred: 'Ett fel har inträffat',
    },
    ee: {
      supportTicketGenerated: 'Toetusticket genereeritud',
      enterIdNumber: 'Sisestage oma ID-number',
      uploadIdentityImage: 'Laadige üles oma ID-dokumendi pilt',
      dataSuccessfullySaved: 'Andmed on edukalt salvestatud',
      passwordSuccessfullyChanged: 'Parool muudetud edukalt',
      deleteReportConfirmation: 'Kas olete kindel, et soovite selle aruande kustutada?',
      ticketNotGenerated: 'Toetusticketit ei genereeritud',
      selectProduct: 'Valige toode',
      enterDescription: 'Sisestage kirjeldus',
      selectLevel: 'Valige tase',
      reportDeleted: 'Aruanne kustutatud',
      addresRequired: 'Aadress on kohustuslik',
      zipCodeRequired: 'Postiindeks on kohustuslik',
      quotationDontBelongToLoggedUser: 'See hinnapakkumine ei kuulu sisseloginud kasutajale',
      priceRequestSentSuccessfully: 'Hinnapäring saadeti edukalt',
      errorHasOcurred: 'Ilmnes viga',
    },
    de: {
      supportTicketGenerated: 'Support-Ticket generiert',
      enterIdNumber: 'Bitte geben Sie Ihre ID-Nummer ein',
      uploadIdentityImage: 'Bitte laden Sie ein Bild Ihres Ausweises hoch',
      dataSuccessfullySaved: 'Daten erfolgreich gespeichert',
      passwordSuccessfullyChanged: 'Passwort erfolgreich geändert',
      deleteReportConfirmation: 'Möchten Sie diesen Bericht wirklich löschen?',
      ticketNotGenerated: 'Support-Ticket nicht generiert',
      selectProduct: 'Bitte wählen Sie ein Produkt',
      enterDescription: 'Bitte geben Sie eine Beschreibung ein',
      selectLevel: 'Bitte wählen Sie eine Ebene',
      reportDeleted: 'Bericht gelöscht',
      addresRequired: 'Adresse ist erforderlich',
      zipCodeRequired: 'Postleitzahl ist erforderlich',
      quotationDontBelongToLoggedUser: 'Dieses Angebot gehört nicht zum angemeldeten Benutzer',
      priceRequestSentSuccessfully: 'Preisanfrage erfolgreich gesendet',
      errorHasOcurred: 'Ein Fehler ist aufgetreten',
    }
  };
  