const alertsTranslations = {
    en: {
      supportTicketGenerated: 'Support ticket generated',
      enterIdNumber: 'Please enter your ID number',
      uploadIdentityImage: 'Please upload an image of your ID',
      dataSuccessfullySaved: 'Data successfully saved',
      passwordSuccessfullyChanged: 'Password successfully changed',
      deleteReportConfirmation: 'Are you sure you want to delete this report?',
      ticketNotGenerated: 'Support ticket not generated',
      selectProduct: 'Please select a product',
      enterDescription: 'Please enter a description',
      selectLevel: 'Please select a level',
      reportDeleted: 'Report deleted',
      addresRequired: 'Address is required',
      zipCodeRequired: 'Zip code is required',
      quotationDontBelongToLoggedUser: 'This quotation does not belong to the logged user',
      priceRequestSentSuccessfully: 'Price request sent successfully',
      errorHasOcurred: 'An error has occurred',
      pleaseFillRequiredFields: 'Please fill the required fields',
      userDoesntExist: 'User does not exist',
      messageSentSuccessfully: 'Message sent successfully',
      pleaseStartUserTagWith: 'Please start user tag with @',
      areYouSureYouWantToSendThisMessage: 'Are you sure you want to send this message?',
      errorSendingMessage: 'Error sending message',
      checkInboxOrSpam: 'Check your inbox or spam folder',
      emailVerified: 'Email verified',
      failedToUpdatePassword: 'Failed to update password',
      linkExpired: 'The link has expired',
      quoteGenerated: 'Quote generated',
      areYouSureYouWantToChangeTheStatus: 'Are you sure you want to change the status',
      selectOption: 'Please select an option!',
      updateSuccessful: 'Update successful!',
    },
    es: {
      supportTicketGenerated: 'Ticket de soporte generado',
      enterIdNumber: 'Por favor ingrese su número de identificación',
      uploadIdentityImage: 'Por favor suba una imagen de su identificación',
      dataSuccessfullySaved: 'Datos guardados exitosamente',
      passwordSuccessfullyChanged: 'Contraseña cambiada exitosamente',
      deleteReportConfirmation: '¿Está seguro de que desea eliminar este reporte?',
      ticketNotGenerated: 'Ticket de soporte no generado',
      selectProduct: 'Por favor seleccione un producto',
      enterDescription: 'Por favor ingrese una descripción',
      selectLevel: 'Por favor seleccione un nivel',
      reportDeleted: 'Reporte eliminado',
      addresRequired: 'Dirección es requerida',
      zipCodeRequired: 'Código postal es requerido',
      quotationDontBelongToLoggedUser: 'Esta cotización no pertenece al usuario logueado',
      priceRequestSentSuccessfully: 'Solicitud de precio enviada exitosamente',
      errorHasOcurred: 'Ha ocurrido un error',
      pleaseFillRequiredFields: 'Por favor llene los campos requeridos',
      userDoesntExist: 'El usuario no existe',
      messageSentSuccessfully: 'Mensaje enviado exitosamente',
      pleaseStartUserTagWith: 'Por favor comience la etiqueta de usuario con @',
      areYouSureYouWantToSendThisMessage: '¿Está seguro de que desea enviar este mensaje?',
      errorSendingMessage: 'Error al enviar mensaje',
      checkInboxOrSpam: 'Revise su bandeja de entrada o carpeta de spam',
      emailVerified: 'Correo verificado',
      failedToUpdatePassword: 'No se pudo actualizar la contraseña',
      linkExpired: 'El enlace ha expirado',
      quoteGenerated: 'Cotización generada',
      areYouSureYouWantToChangeTheStatus: '¿Está seguro de que desea cambiar el estado',
      selectOption: '¡Por favor seleccione una opción!',
      updateSuccessful: '¡Actualización exitosa!'
    },
    fr: {
      supportTicketGenerated: 'Ticket de support généré',
      enterIdNumber: 'Veuillez entrer votre numéro d\'identification',
      uploadIdentityImage: 'Veuillez télécharger une image de votre pièce d\'identité',
      dataSuccessfullySaved: 'Données enregistrées avec succès',
      passwordSuccessfullyChanged: 'Mot de passe changé avec succès',
      deleteReportConfirmation: 'Êtes-vous sûr de vouloir supprimer ce rapport?',
      ticketNotGenerated: 'Ticket de support non généré',
      selectProduct: 'Veuillez sélectionner un produit',
      enterDescription: 'Veuillez entrer une description',
      selectLevel: 'Veuillez sélectionner un niveau',
      reportDeleted: 'Rapport supprimé',
      addresRequired: 'Adresse est requise',
      zipCodeRequired: 'Code postal est requis',
      quotationDontBelongToLoggedUser: 'Cette citation n\'appartient pas à l\'utilisateur connecté',
      priceRequestSentSuccessfully: 'Demande de prix envoyée avec succès',
      errorHasOcurred: 'Une erreur s\'est produite',
      pleaseFillRequiredFields: 'Veuillez remplir les champs requis',
      userDoesntExist: 'L\'util isateur n\'existe pas',
      messageSentSuccessfully: 'Message envoyé avec succès',
      pleaseStartUserTagWith: 'Veuillez commencer la balise utilisateur avec @',
      areYouSureYouWantToSendThisMessage: 'Êtes-vous sûr de vouloir envoyer ce message?',
      errorSendingMessage: 'Erreur lors de l\'envoi du message',
      checkInboxOrSpam: 'Vérifiez votre boîte de réception ou votre dossier de spam',
      emailVerified: 'Email vérifié',
      failedToUpdatePassword: 'Échec de la mise à jour du mot de passe',
      linkExpired: 'Le lien a expiré',
      quoteGenerated: 'Devis généré',
      areYouSureYouWantToChangeTheStatus: 'Êtes-vous sûr de vouloir changer le statut',
      selectOption: 'Veuillez sélectionner une option!',
      updateSuccessful: 'Mise à jour réussie!',
    },
    it: {
      supportTicketGenerated: 'Ticket di supporto generato',
      enterIdNumber: 'Si prega di inserire il numero di identificazione',
      uploadIdentityImage: 'Si prega di caricare un\'immagine del documento di identità',
      dataSuccessfullySaved: 'Dati salvati con successo',
      passwordSuccessfullyChanged: 'Password modificata con successo',
      deleteReportConfirmation: 'Sei sicuro di voler eliminare questo report?',
      ticketNotGenerated: 'Ticket di supporto non generato',
      selectProduct: 'Si prega di selezionare un prodotto',
      enterDescription: 'Si prega di inserire una descrizione',
      selectLevel: 'Si prega di selezionare un livello',
      reportDeleted: 'Report eliminato',
      addresRequired: 'Indirizzo richiesto',
      zipCodeRequired: 'Il codice postale è richiesto',
      quotationDontBelongToLoggedUser: 'Questa citazione non appartiene all\'utente connesso',
      priceRequestSentSuccessfully: 'Richiesta di prezzo inviata con successo',
      errorHasOcurred: 'Si è verificato un errore',
      pleaseFillRequiredFields: 'Si prega di compilare i campi obbligatori',
      userDoesntExist: 'L\'utente non esiste',
      messageSentSuccessfully: 'Messaggio inviato con successo',
      pleaseStartUserTagWith: 'Si prega di iniziare il tag utente con @',
      areYouSureYouWantToSendThisMessage: 'Sei sicuro di voler inviare questo messaggio?',
      errorSendingMessage: 'Errore nell\'invio del messaggio',
      checkInboxOrSpam: 'Controlla la tua casella di posta in arrivo o la cartella dello spam',
      emailVerified: 'Email verificata',
      failedToUpdatePassword: 'Aggiornamento della password non riuscito',
      linkExpired: 'Il link è scaduto',
      quoteGenerated: 'Preventivo generato',
      areYouSureYouWantToChangeTheStatus: 'Sei sicuro di voler cambiare lo stato',
      selectOption: 'Si prega di selezionare un\'opzione!',
      updateSuccessful: 'Aggiornamento riuscito!',
    },
    pt: {
      supportTicketGenerated: 'Bilhete de suporte gerado',
      enterIdNumber: 'Por favor, insira o número de identificação',
      uploadIdentityImage: 'Por favor, faça o upload de uma imagem do seu documento de identidade',
      dataSuccessfullySaved: 'Dados salvos com sucesso',
      passwordSuccessfullyChanged: 'Senha alterada com sucesso',
      deleteReportConfirmation: 'Tem certeza de que deseja excluir este relatório?',
      ticketNotGenerated: 'Bilhete de suporte não gerado',
      selectProduct: 'Por favor, selecione um produto',
      enterDescription: 'Por favor, insira uma descrição',
      selectLevel: 'Por favor, selecione um nível',
      reportDeleted: 'Relatório excluído',
      addresRequired: 'Endereço é obrigatório',
      zipCodeRequired: 'O código postal é obrigatório',
      quotationDontBelongToLoggedUser: 'Esta cotação não pertence ao usuário logado',
      priceRequestSentSuccessfully: 'Pedido de preço enviado com sucesso',
      errorHasOcurred: 'Ocorreu um erro',
      pleaseFillRequiredFields: 'Por favor, preencha os campos obrigatórios',
      userDoesntExist: 'O usuário não existe',
      messageSentSuccessfully: 'Mensagem enviada com sucesso',
      pleaseStartUserTagWith: 'Por favor, comece a tag do usuário com @',
      areYouSureYouWantToSendThisMessage: 'Tem certeza de que deseja enviar esta mensagem?',
      errorSendingMessage: 'Erro ao enviar mensagem',
      checkInboxOrSpam: 'Verifique sua caixa de entrada ou pasta de spam',
      emailVerified: 'E-mail verificado',
      failedToUpdatePassword: 'Falha ao atualizar a senha',
      linkExpired: 'O link expirou',
      quoteGenerated: 'Cotação gerada',
      areYouSureYouWantToChangeTheStatus: 'Tem certeza de que deseja alterar o status',
      selectOption: 'Por favor, selecione uma opção!',
      updateSuccessful: 'Atualização bem-sucedida!',
    },
    pl: {
      supportTicketGenerated: 'Bilet wsparcia wygenerowany',
      enterIdNumber: 'Proszę podać swój numer identyfikacyjny',
      uploadIdentityImage: 'Proszę przesłać obraz swojego dokumentu tożsamości',
      dataSuccessfullySaved: 'Dane zapisane pomyślnie',
      passwordSuccessfullyChanged: 'Hasło zostało pomyślnie zmienione',
      deleteReportConfirmation: 'Czy na pewno chcesz usunąć ten raport?',
      ticketNotGenerated: 'Bilet ws parcia nie wygenerowany',
      selectProduct: 'Proszę wybrać produkt',
      enterDescription: 'Proszę wprowadzić opis',
      selectLevel: 'Proszę wybrać poziom',
      reportDeleted: 'Raport usunięty',
      addresRequired: 'Adres jest wymagany',
      zipCodeRequired: 'Kod pocztowy jest wymagany',
      quotationDontBelongToLoggedUser: 'To zapytanie nie należy do zalogowanego użytkownika',
      priceRequestSentSuccessfully: 'Zapytanie o cenę wysłane pomyślnie',
      errorHasOcurred: 'Wystąpił błąd',
      pleaseFillRequiredFields: 'Proszę wypełnić wymagane pola',
      userDoesntExist: 'Użytkownik nie istnieje',
      messageSentSuccessfully: 'Wiadomość wysłana pomyślnie',
      pleaseStartUserTagWith: 'Proszę zacząć tag użytkownika od @',
      areYouSureYouWantToSendThisMessage: 'Czy na pewno chcesz wysłać tę wiadomość?',
      errorSendingMessage: 'Błąd podczas wysyłania wiadomości',
      checkInboxOrSpam: 'Sprawdź swoją skrzynkę odbiorczą lub folder ze spamem',
      emailVerified: 'E-mail zweryfikowany',
      failedToUpdatePassword: 'Nie udało się zaktualizować hasła',
      linkExpired: 'Link wygasł',
      quoteGenerated: 'Zapytanie o cenę zostało wysłane',
      areYouSureYouWantToChangeTheStatus: 'Czy na pew no chcesz zmienić status',
      selectOption: 'Proszę wybrać opcję!',
      updateSuccessful: 'Aktualizacja zakończona sukcesem!',
    },
    nl: {
      supportTicketGenerated: 'Ondersteuningsticket gegenereerd',
      enterIdNumber: 'Voer uw ID-nummer in',
      uploadIdentityImage: 'Upload een afbeelding van uw identiteitsbewijs',
      dataSuccessfullySaved: 'Gegevens succesvol opgeslagen',
      passwordSuccessfullyChanged: 'Wachtwoord succesvol gewijzigd',
      deleteReportConfirmation: 'Weet u zeker dat u dit rapport wilt verwijderen?',
      ticketNotGenerated: 'Ondersteuningsticket niet gegenereerd',
      selectProduct: 'Selecteer een product',
      enterDescription: 'Voer een beschrijving in',
      selectLevel: 'Selecteer een niveau',
      reportDeleted: 'Rapport verwijderd',
      addresRequired: 'Adres is verplicht',
      zipCodeRequired: 'Postcode is verplicht',
      quotationDontBelongToLoggedUser: 'Deze offerte behoort niet tot de ingelogde gebruiker',
      priceRequestSentSuccessfully: 'Prijsaanvraag succesvol verzonden',
      errorHasOcurred: 'Er is een fout opgetreden',
      pleaseFillRequiredFields: 'Vul de verplichte velden in',
      userDoesntExist: 'Gebruiker bestaat niet',
      messageSentSuccessfully: 'Bericht succesvol verzonden',
      pleaseStartUserTagWith: 'Begin de gebruikerstag met @',
      areYouSureYouWantToSendThisMessage: 'Weet u zeker dat u dit bericht wilt verzenden?',
      errorSendingMessage: 'Fout bij het verzenden van het bericht',
      checkInboxOrSpam: 'Controleer uw inbox of spammap',
      emailVerified: 'E-mail geverifieerd',
      failedToUpdatePassword: 'Wacht woord bijwerken mislukt',
      linkExpired: 'De link is verlopen',
      quoteGenerated: 'Offerte gegenereerd',
      areYouSureYouWantToChangeTheStatus: 'Weet u zeker dat u de status wilt wijzigen',
      selectOption: 'Selecteer alstublieft een optie!',
      updateSuccessful: 'Update succesvol!',
    },
    sv: {
      supportTicketGenerated: 'Supportbiljett genererad',
      enterIdNumber: 'Ange ditt ID-nummer',
      uploadIdentityImage: 'Ladda upp en bild av ditt ID',
      dataSuccessfullySaved: 'Data sparades framgångsrikt',
      passwordSuccessfullyChanged: 'Lösenordet ändrades framgångsrikt',
      deleteReportConfirmation: 'Är du säker på att du vill ta bort denna rapport?',
      ticketNotGenerated: 'Supportbiljett inte genererad',
      selectProduct: 'Vänligen välj en produkt',
      enterDescription: 'Ange en beskrivning',
      selectLevel: 'Vänligen välj en nivå',
      reportDeleted: 'Rapport raderad',
      addresRequired: 'Adress krävs',
      zipCodeRequired: 'Postnummer krävs',
      quotationDontBelongToLoggedUser: 'Denna offert tillhör inte den inloggade användaren',
      priceRequestSentSuccessfully: 'Prisförfrågan skickades framgångsrikt',
      errorHasOcurred: 'Ett fel har inträffat',
      pleaseFillRequiredFields: 'Fyll i de obligatoriska fälten',
      userDoesntExist: 'Användaren finns inte',
      messageSentSuccessfully: 'Meddelandet skickades framgångsrikt',
      pleaseStartUserTagWith: 'Börja användartaggen med @',
      areYouSureYouWantToSendThisMessage: 'Är du säker på att du vill skicka detta meddelande?',
      errorSendingMessage: 'Fel vid sändning av meddelande',
      checkInboxOrSpam: 'Kontrollera din inkorg eller skräppostmapp',
      emailVerified: 'E-post verifierad',
      failedToUpdatePassword: 'Miss lyckades med att uppdatera lösenordet',
      linkExpired: 'Länken har gått ut',
      quoteGenerated: 'Offert genererad',
      areYouSureYouWantToChangeTheStatus: 'Är du säker på att du vill ändra status',
      selectOption: 'Vänligen välj ett alternativ!',
      updateSuccessful: 'Uppdatering lyckades!',
    },
    ee: {
      supportTicketGenerated: 'Toetusticket genereeritud',
      enterIdNumber: 'Sisestage oma ID-number',
      uploadIdentityImage: 'Laadige üles oma ID-dokumendi pilt',
      dataSuccessfullySaved: 'Andmed on edukalt salvestatud',
      passwordSuccessfullyChanged: 'Parool muudetud edukalt',
      deleteReportConfirmation: 'Kas olete kindel, et soovite selle aruande kustutada?',
      ticketNotGenerated: 'Toetusticketit ei genereeritud',
      selectProduct: 'Valige toode',
      enterDescription: 'Sisestage kirjeldus',
      selectLevel: 'Valige tase',
      reportDeleted: 'Aruanne kustutatud',
      addresRequired: 'Aadress on kohustuslik',
      zipCodeRequired: 'Postiindeks on kohustuslik',
      quotationDontBelongToLoggedUser: 'See hinnapakkumine ei kuulu sisseloginud kasutajale',
      priceRequestSentSuccessfully: 'Hinnapäring saadeti edukalt',
      errorHasOcurred: 'Ilmnes viga',
      pleaseFillRequiredFields: 'Palun täitke nõutud väljad',
      userDoesntExist: 'Kasutajat ei eksisteeri',
      messageSentSuccessfully: 'Sõnum saadeti edukalt',
      pleaseStartUserTagWith: 'Alustage kasutaja sildiga @',
      areYouSureYouWantToSendThisMessage: 'Olete kindel, et soovite selle sõnumi saata?',
      errorSendingMessage: 'Viga sõnumi saatmisel',
      checkInboxOrSpam: 'Kontrollige oma postkasti või rämpsposti kausta',
      emailVerified: 'E-post kontrollitud',
      failedToUpdatePassword: 'Parooli värskendamine ebaõnnestus',
      linkExpired: 'Link on aegunud',
      quoteGenerated: 'Pakkumine genereeritud',
      areYouSureYouWantToChangeTheStatus: 'Olete kindel, et soovite olekut muuta',
      selectOption: 'Palun valige valik!',
      updateSuccessful: 'Uuendamine õnnestus!',
    },
    de: {
      supportTicketGenerated: 'Support-Ticket generiert',
      enterIdNumber: 'Bitte geben Sie Ihre ID-Nummer ein',
      uploadIdentityImage: 'Bitte laden Sie ein Bild Ihres Ausweises hoch',
      dataSuccessfullySaved: 'Daten erfolgreich gespeichert',
      passwordSuccessfullyChanged: 'Passwort erfolgreich geändert',
      deleteReportConfirmation: 'Möchten Sie diesen Bericht wirklich löschen?',
      ticketNotGenerated: 'Support-Ticket nicht generiert',
      selectProduct: 'Bitte wählen Sie ein Produkt',
      enterDescription: 'Bitte geben Sie eine Beschreibung ein',
      selectLevel: 'Bitte wählen Sie eine Ebene',
      reportDeleted: 'Bericht gelöscht',
      addresRequired: 'Adresse ist erforderlich',
      zipCodeRequired: 'Postleitzahl ist erforderlich',
      quotationDontBelongToLoggedUser: 'Dieses Angebot gehört nicht zum angemeldeten Benutzer',
      priceRequestSentSuccessfully: 'Preisanfrage erfolgreich gesendet',
      errorHasOcurred: 'Ein Fehler ist aufgetreten',
      pleaseFillRequiredFields: 'Bitte füllen Sie die erforderlichen Felder aus',
      userDoesntExist: 'Benutzer existiert nicht',
      messageSentSuccessfully: 'Nachricht erfolgreich gesendet',
      pleaseStartUserTagWith: 'Bitte beginnen Sie den Benutzertag mit @',
      areYouSureYouWantToSendThisMessage: 'Sind Sie sicher, dass Sie diese Nachricht senden möchten?',
      errorSendingMessage: 'Fehler beim Senden der Nachricht',
      checkInboxOrSpam: 'Überprüfen Sie Ihren Posteingang oder Spam-Ordner',
      emailVerified: 'E-Mail verifiziert',
      failedToUpdatePassword: 'Fehler beim Aktualisieren des Passworts',
      linkExpired: 'Der Link ist abgelaufen',
      quoteGenerated: 'Angebot generiert',
      areYouSureYouWantToChangeTheStatus: 'Sind Sie sicher, dass Sie den Status ändern möchten',
      selectOption: 'Bitte wählen Sie eine Option!',
      updateSuccessful: 'Aktualisierung erfolgreich!',
    }
  };
  